using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Abubu.Audio;
using Abubu.Effects;
using UnityEditor;
using UnityEngine;

namespace Abubu.Editor
{
    /// <summary>
    /// Tools > Abubu > Generate Keys
    /// SoundLibrary / EffectLibrary に登録されたキーから、文字列リテラルの代わりに使える定数クラスを生成する。
    /// <code>
    /// Sound.PlaySe(SoundKeys.Se.Jump);        // "jump" と書くより、タイポがコンパイルエラーになる
    /// Fx.Play(EffectKeys.Explosion, pos);
    /// </code>
    /// </summary>
    /// <remarks>
    /// 出力先は Assets/Abubu/Generated/AbubuKeys.cs。内容が変わらなければ書き込まないので、何度実行しても安全。
    /// ライブラリを編集したら再実行すること (自動では更新されない)。
    /// </remarks>
    public static class AbubuKeyGenerator
    {
        private const string OutputFolder = "Assets/Abubu/Generated";
        private const string OutputPath = OutputFolder + "/AbubuKeys.cs";

        [MenuItem("Tools/Abubu/Generate Keys", priority = 20)]
        public static void Generate()
        {
            var source = Build(CollectSoundKeys(), CollectEffectKeys());

            if (File.Exists(OutputPath) && File.ReadAllText(OutputPath) == source)
            {
                Debug.Log($"[Abubu] キー定数は最新です: {OutputPath}");
                return;
            }

            Directory.CreateDirectory(OutputFolder);
            File.WriteAllText(OutputPath, source, new UTF8Encoding(false));
            AssetDatabase.ImportAsset(OutputPath);
            Debug.Log($"[Abubu] キー定数を生成しました: {OutputPath}");
        }

        /// <summary>カテゴリ → キー一覧。プロジェクト内の全 SoundLibrary (includes 先を含む) を集める</summary>
        private static Dictionary<SoundCategory, List<string>> CollectSoundKeys()
        {
            var libraries = FindAssets<SoundLibrary>();
            var result = new Dictionary<SoundCategory, List<string>>();
            foreach (SoundCategory category in Enum.GetValues(typeof(SoundCategory)))
            {
                result[category] = libraries.SelectMany(l => l.GetKeys(category)).Distinct().OrderBy(k => k, StringComparer.Ordinal).ToList();
            }
            return result;
        }

        private static List<string> CollectEffectKeys() =>
            FindAssets<EffectLibrary>().SelectMany(l => l.Keys).Distinct().OrderBy(k => k, StringComparer.Ordinal).ToList();

        private static List<T> FindAssets<T>() where T : UnityEngine.Object =>
            AssetDatabase.FindAssets($"t:{typeof(T).Name}", new[] { "Assets" })
                .Select(guid => AssetDatabase.LoadAssetAtPath<T>(AssetDatabase.GUIDToAssetPath(guid)))
                .Where(a => a != null)
                .ToList();

        /// <summary>生成するソースコードを組み立てる (テストしやすいよう副作用なし)</summary>
        internal static string Build(IReadOnlyDictionary<SoundCategory, List<string>> sound, IReadOnlyList<string> effects)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Tools > Abubu > Generate Keys で生成されました。手で編集しないでください。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("namespace Abubu");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>SoundLibrary のキー定数</summary>");
            sb.AppendLine("    public static class SoundKeys");
            sb.AppendLine("    {");
            foreach (var category in new[] { SoundCategory.Bgm, SoundCategory.Se, SoundCategory.Ambient })
            {
                sb.AppendLine($"        public static class {category}");
                sb.AppendLine("        {");
                AppendConstants(sb, sound.TryGetValue(category, out var keys) ? keys : new List<string>(), "            ", category.ToString());
                sb.AppendLine("        }");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>EffectLibrary のキー定数</summary>");
            sb.AppendLine("    public static class EffectKeys");
            sb.AppendLine("    {");
            AppendConstants(sb, effects, "        ", "EffectKeys");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void AppendConstants(StringBuilder sb, IEnumerable<string> keys, string indent, string ownerName)
        {
            var used = new HashSet<string>();
            foreach (var key in keys)
            {
                var name = ToIdentifier(key);
                // メンバー名は囲んでいる型と同じにできない (例: SoundKeys.Se の中の "se")
                if (name == ownerName) name += "_";
                // 別のキーが同じ識別子になる場合は連番で区別する
                var unique = name;
                for (var i = 2; !used.Add(unique); i++) unique = name + i;
                sb.AppendLine($"{indent}public const string {unique} = \"{Escape(key)}\";");
            }
        }

        /// <summary>"title_bgm" → "TitleBgm"、"1up" → "_1up" (先頭は必ず大文字になるため予約語とは衝突しない)</summary>
        internal static string ToIdentifier(string key)
        {
            var sb = new StringBuilder();
            var upperNext = true;
            foreach (var c in key)
            {
                if (!char.IsLetterOrDigit(c))
                {
                    upperNext = true;
                    continue;
                }
                sb.Append(upperNext ? char.ToUpperInvariant(c) : c);
                upperNext = false;
            }

            if (sb.Length == 0) return "_";
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');

            return sb.ToString();
        }

        private static string Escape(string key) => key.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
